# -*- mode:python -*-

Import('*')

SimObject('UACC.py', sim_objects=[
    'UACCController',
    'UACCSelector',
    'UACCCache',
    'UACCPartitionManager',
    'UACCCapacityPolicy',
])

Source('uacc_controller.cc')
Source('uacc_selector.cc')
Source('uacc_cache.cc')
Source('uacc_partition.cc')

GTest('uacc_queue_model.test', 'uacc_queue_model.test.cc')

DebugFlag('UACC')
